### ISSUE TITLE
Ask the log server for a list of attempts per routing key

### ISSUE THREAD

**Issue by grahamc** [samueldr/logger-wip#2]
(please prioritize over #1)

Given https://nix.samueldr.com/temp/?key=foobar123 query https://logs.nix.gsc.io/logs/foobar123 for known attempt logs in this format:

```json
{
 "attempts": [ "foo", "bar", "baz"]
}
```

which correlates to attempts at:

 - https://logs.nix.gsc.io/logs/foobar123/foo
 - https://logs.nix.gsc.io/logs/foobar123/bar
 - https://logs.nix.gsc.io/logs/foobar123/baz

and show these as tabs in the UI.

**Comment by samueldr** [comment]
Is there still an assumption that a new attempt can be added at any moment through the queue? Not that it's an issue, but if not this'll make the code smaller.

**Comment by grahamc** [comment]
Hmm yes probably should keep that assumption, where this list provided list
is merged with any attempts “discovered” via the rabbitmq stream.

**Comment by grahamc** [comment]
OK, This API is now up: https://logs.nix.gsc.io/logs/nixos/nixpkgs.34107/

```json
{
   "attempts": {
    "d0f5ca14-b7cf-4660-aaad-83e64f6f873b":{
      "log_url":"https:\/\/logs.nix.gsc.io\/\/logs\/nixos\/nixpkgs.34107\/\/d0f5ca14-b7cf-4660-aaad-83e64f6f873b"
    },
    "7db796d3-4da3-4ac5-bc31-55655a2a6ecb":{
      "log_url":"https:\/\/logs.nix.gsc.io\/\/logs\/nixos\/nixpkgs.34107\/\/7db796d3-4da3-4ac5-bc31-55655a2a6ecb"
    }
  }
}
```

I've changed this API to return a more robust format to allow me to send logs to a different server in the future, or include per-attempt details.

Logs are currently pruned after a few days, so this URL may cease to work in the future.

**Comment by samueldr** [comment]
> ⚠️ Failed to load https://logs.nix.gsc.io/logs/nixos/nixpkgs.34107: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by grahamc** [comment]
Looks great!
