### ISSUE TITLE
(low priority) When fetching the backlog for a job, use the routing key identified in the delivered message instead of the key provided in the URL

### ISSUE THREAD

**Issue by grahamc** [samueldr/logger-wip#3]
When viewing https://nix.samueldr.com/temp/?key=*.* a job came up with the attempt ID `7db796d3-4da3-4ac5-bc31-55655a2a6ecb`. When I clicked the tab, the website tried to load logs from `https://logs.nix.gsc.io/logs/*.*/7db796d3-4da3-4ac5-bc31-55655a2a6ecb` instead of identifying from the routing key provided in the message that it should look `https://logs.nix.gsc.io/logs/nixos/nixpkgs.34107/7db796d3-4da3-4ac5-bc31-55655a2a6ecb`

Here is an example of headers provided when the message arrives:

```
subscription:sub-0
destination:/exchange/logs/nixos%2Fnixpkgs.34107
message-id:T_sub-0@@session-d18JUPP8yd_covcEQNgNuQ@@1
redelivered:false
content-type:application/json
content-length:611
```

I'd propose the destination be parsed to determine the routing key for the log.

Not many people will be using this URL to view logs, so I think it isn't a big deal if this is never done.

**Comment by samueldr** [comment]
*Pushed a "fixes" commit even though it isn't verified to be fixed, re-opening*

**Comment by grahamc** [comment]
Verified it works!
